[server]
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "minimal"
